#!/bin/awk -f

#################################################################################
#
#	About:
# 	Put each sequence part of a fasta file on a single line per entry 
#
#	Usage:
#	cat example/file.fa | fastajoinlines
#
#	Example: Suppose
#	$ cat example/file.fa 
#	>1
#	CGAATGGGTAAACGAATCTGACGTTGAAGAGTTCCGCACAAAAGAAGATTTAAACTATTA
#	ATAAGGGGTAGTTAGCTATGTTAAACGTAGAAATTCGGTATAACAAAGACTGTTCTGTAG
#
#	$ cat example/file.fa | fastajoinlines
#	>1
#	CGAATGGGTAAACGAATCTGACGTTGAAGAGTTCCGCACAAAAGAAGATTTAAACTATTAATAAGGGGTAGTTAGCTATGTTAAACGTAGAAATTCGGTATAACAAAGACTGTTCTGTAG
#	
#	Notes: 
#	To undo, use unix fold. E.g., 
#
#	$ cat example/file.fa | fastajoinlines | fold -w 60
#
#	Author:
#
# 	V Trifonov 2012. contact: vladot@c2b2.columbia.edu
#  
################################################################################################################

BEGIN{f=0}
{if ($0~/^>/) {if (f) printf "\n"; print $0; f=1} else printf $0}
END{printf "\n"}
