#!/usr/bin/env bash

# About:
# Add a line to number fields at the top of a text file

# Example:
# Suppose that 
# $ cat example/file1.txt
# a	asdfasfd	c
# a	a		e

# Useage:
# $ cat example/file1.txt | colcount 

# The outcome is:
# $ cat example/file1.txt | colcount 
# 1	2		3
# a	asdfasfd	c
# a	a		e

# help section
myhelp=$( cat <<_EOF_

add numbers to columns

Usage:

cat file | colcount

Example:

\$ cat test1
a	a
b	d
\$ cat test1 | colcount
1	2
a	a
b	d

_EOF_ 
)

if [  "$1" == "-h" -o "$1" == "-help" -o "$1" == "--help" ]; then
	shift; echo "$myhelp"; exit;
fi

# use the fact a tab is 8 characters

awk -F"\t" '{if (NR==1) { for (i=1; i<=NF; i++) {printf i; for (j=1; j<=int(length($i)/8); j++) {printf "\t"}; if (i==NF) {printf "\n"} else {printf "\t"}}; print $0 } else {print $0}}'
