#!/usr/bin/env perl

my $usage = <<_EOUSAGE_;

################################################################################################################
#
#	Count the number of occurrences of identical lines in a sorted file
#
#	Usage:
#
#	tablecount <file>
#	cat file | tablecount
#
#	Example:
#	
#	Suppose
#
#	\$ cat test | sort -k1,1n 
#	1	a
#	1	a
#	1	a
#	1	b
#	1	b
#	2	c
#	3	d
#	
#	Then
#	\$ cat test | sort -k1,1n | tablecount
#	1	a	3
#	1	b	2
#	2	c	1
#	3	d	1
#
#	Author:
#
# 	V Trifonov 2012. contact: vladot\@c2b2.columbia.edu
#  
################################################################################################################

_EOUSAGE_

if ( $ARGV[0] eq "-h" || $ARGV[0] eq "-help" || $ARGV[0] eq "--help" ) { print $usage; exit; }

$q = ""; $i = 0;
while (<>) 
{
	chomp;
	$i = $i + 1;
	if ($_ ne $q) 
	{
		print $q."\t".($i-1)."\n" if ($q ne "");
		$i = 1;
		$q = $_;
	}
}
print $q."\t".$i."\n";
